name: tinkoff_acquiring
description: Flutter Tinkoff Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 3.0.11
repository: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  comparer: ^2.0.1
  crypto: ^3.0.3
  crypton: ^2.1.0
  http: ^1.0.0
  meta: ^1.9.1
  json_annotation: ^4.5.0

dev_dependencies:
  test: ^1.21.3
  build_runner: ^2.4.4
  json_serializable: ^6.7.0