name: tinkoff_acquiring_flutter
description: Flutter Tinkoff Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 3.0.5
repository: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tinkoff_acquiring: ^3.0.5
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: